fix: adjust type to remove need for `@types/lodash`
bcherny/json-schema-to-typescript pull request #362
Opened 2021-01-11 18:30 UTC by G-Rath

I actually thought this was because of #361 but it's not - not sure why it didn't error in the past on the same project.

Originally I was going to add `@types/lodash` to `dependencies`, but realised I could explicitly type the export to make it not needed.

2021-01-13 04:45 UTC, sempasha approved these changes

2021-01-17 21:06 UTC, bcherny requested changes
Hey, thanks for the contribution! Could we add the dependency on `@types/lodash` instead? Otherwise, without a way to add a test for this, this is likely to silently regress in the future (eg. next time someone refactors this function, and chooses to remove the unnecessary type annotation).

2021-01-18 18:13 UTC, G-Rath commented
@bcherny ugh that's a very good point 🤦‍♂️

A possible way to guard against that could be to export the `memoize` from a local file with a wrapper and comment explaining why, so that everything would use that `memoize`.

2021-01-18 18:17 UTC, G-Rath commented
(btw I've made some PRs to update the browser version to [the latest major](https://github.com/bcherny/json-schema-to-typescript-browser/pull/5) 🙂)

2021-01-18 21:05 UTC, bcherny approved these changes
Thanks for updating!

2021-01-18 21:05 UTC, merged

2021-01-18 21:06 UTC, bcherny commented
Published 10.1.3

2024-08-30 16:06 UTC, utajum commented
I am seeing this error with versions >= 15

Versions below 15 work fine