Allow specification of a custom interface name
bcherny/json-schema-to-typescript pull request #456
Opened 2022-06-07 02:31 UTC by queengooborg

This PR adds a new `tsName` schema property that allows a developer to overwrite the default generated name.  This is super helpful in cases where two interfaces/types are generated with the same name (and one has a numerical increment), or where the developer may wish to ensure backwards compatibility of their TypeScript definitions.

Before:

```ts
/**
 * This interface was referenced by `Browsers`'s JSON-Schema
 * via the `definition` "browsers".
 */
export type Browsers1 = Record<string, BrowserStatement>;

export interface Browsers {
  browsers?: Browsers1;
}
```

After:

```ts
/**
 * This interface was referenced by `Browsers`'s JSON-Schema
 * via the `definition` "browsers".
 */
export type Browsers = Record<string, BrowserStatement>;

export interface BrowsersData {
  browsers?: Browsers;
}
```

This is related to #181 (and potentially resolves it?).  Unlike #215, however, this PR aims to grant the developer more finite control over the names.

2022-06-11 06:00 UTC, bcherny requested changes
Seems reasonable! A few minor suggestions before we merge this.

2022-06-11 06:00 UTC, bcherny commented on README.md
> +- `tsName`: Overrides the name of a generated interface from the schema. Useful if two items are generated with similar names.
Could you call this `x-name`? We'll be renaming `tsType` and `tsEnumNames` soon to match the new convention.

2022-06-11 23:17 UTC, queengooborg commented on test/e2e/customName.ts
> +  tsName: 'GroceryList'
I didn't realize that `title` was an actual schema property!  In that case, the `title` property solves the problem for our use case, but I'll still update the tests and see this PR through to the end!

2022-06-12 00:04 UTC, bcherny commented on test/e2e/customName.ts
> +  tsName: 'GroceryList'
If title works for your use case, we can also pause the work on this PR. No need to add more options unless there’s strong demand for them.

2023-05-04 10:21 UTC, closed without merging