fix: update @apidevtools/json-schema-ref-parser version
bcherny/json-schema-to-typescript pull request #512
Opened 2023-02-20 17:14 UTC by giovanniandreuzza

With the last versione they released, the node version used has been downgraded to 16.

2023-02-20 18:18 UTC, DanRibbens approved these changes

2023-02-21 12:22 UTC, DanRibbens commented
> @DanRibbens what do i have to do in order to have the PR ready to be merged? I really need this fix for my company

I don't manage this repo.
We pinned the version of this package for Payload CMS and we are releasing it today so we don't have to wait on this getting released.

2023-02-23 03:31 UTC, bcherny requested changes
Unfortunately it's not this simple, since 10.1 is not backwards-compatible, and I'm struggling a bit to figure out how to upgrade to it -- it will require a couple upstream fixes to the JSRP exported types, and type lib dependencies. JSRP should have bumped to 11.0 instead 😬.

Continuing the convo in #511.

2023-05-04 10:24 UTC, bcherny commented
Closing out stale PRs. Feel free to rebase and re-open if you'd like to revisit this PR.

2023-05-04 10:24 UTC, closed without merging