fix: generate same title one types
bcherny/json-schema-to-typescript pull request #516
Opened 2023-02-24 02:32 UTC by ianfuin

If two schemas are (a) identical and (b) have the same explicit title, then emit just one type to represent the schema

fix #510

2023-03-20 17:05 UTC, jemand771 commented
hi @ianfuin and thanks for giving this a shot :D

this mostly works for me, but I think I've found a small regression:
```json
{
    "anyOf": [
        {
            "title": "host",
            "enum": [
                "example.com",
                "localhost"
            ]
        },
        {
            "title": "ip",
            "enum": [
                "123.123.123.123"
            ]
        }
    ],
    "type": "string",
    "title": "server"
}
```
would previously turn into
```ts
export type Server = Server1 & Server2;
export type Server1 = Host | Ip;
export type Host = "example.com" | "localhost";
export type Ip = "123.123.123.123";
export type Server2 = string;
```
but is now
```ts
export type Server = Server;
```
all while calling `compile` with the following options:
```js
compile(
        schema,
        undefined,
        {
            bannerComment: "",
            additionalProperties: false,
            strictIndexSignatures: true,
            sameExplicitTitle: sameExplicitTitle,
        }
    );
```
The example above is inspired by an `anyOf` schema with `{"format": "ipv4"}` and `{"format": "hostname"}`, which this lib doesn't seem to support - the `enum` keys are just there to make it at least a tiny bit realistic, but leaving them out gives a similar result.

I can "solve" this by removing either `type` or `title` from the outmost object. I can understand removing the title as it's redundant, but the type should just work like that[^factoring]

[^factoring]: https://json-schema.org/understanding-json-schema/reference/combining.html#id11

2023-03-20 17:15 UTC, jemand771 commented
hm, I can also trigger the `type Foo = Foo;` case using just
```js
import { compile } from 'json-schema-to-typescript/dist/index.js';

console.log(await compile(
    {
        title: "host",
        tsType: "Host"
    },
    undefined,
    {
        bannerComment: ""
    }
));
```
which yields
```ts
export type Host = Host;
```
BUT that also happens without `sameExplicitTitle` set. maybe I'm just using `tsType` wrong, but it still feels related.
possibly also related to #466 (`export type StatusBlock = StatusBlock;` there)

2023-04-23 10:02 UTC, bcherny requested changes
I might be misreading your code, but where do you check that two schemas are identical? With your code, it seems like if two schemas share the same name they will share the same emitted type, even if their properties are completely different.

This also needs more tests, and it should be the default behavior (not behind a flag).

2023-05-04 10:24 UTC, bcherny commented
Closing out stale PRs. Feel free to rebase and re-open if you'd like to revisit this PR.

2023-05-04 10:24 UTC, closed without merging